"""added chore id foreign key

Revision ID: 052ab502447b
Revises: 24941bcb9b9a
Create Date: 2023-09-09 14:02:21.423629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052ab502447b'
down_revision: Union[str, None] = '24941bcb9b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chores', sa.Column('chore_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chores', 'people', ['chore_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chores', type_='foreignkey')
    op.drop_column('chores', 'chore_id')
    # ### end Alembic commands ###
